[package]
name = "ac_internal"
version = "0.1.0"

[lib]
name = "ac_internal"
crate-type = ["cdylib"]

[build-dependencies]
bindgen = "0.70.1"
cc = "1.1.31"

[dependencies]
ctor = "0.2.8"
libloading = "0.8.5"
nix = { version = "0.29.0", features = ["mman"] }
